### ISSUE TITLE
Swallows regular output

### ISSUE THREAD

**Issue by Andarist** [rickhanlonii/jest-skipped-reporter#1]
It seems that this swallows regular jest output. Would be nice to have this reported output something extra once ALL tests are finished.

**Comment by rickhanlonii** [comment]
Hey @Andarist, this reporter is designed to be used in addition to existing reporters which are responsible for the regular output you want to see

For example, you can configure this reporter to be run after the default:

```js
{
  "reporters": ["default", "jest-skipped-reporter"],
}
```

That would output something like:

![](http://dp.hanlon.io/0i3P1S0G2Z0Y/Image%202018-03-18%20at%202.00.16%20PM.png)

**Comment by Andarist** [comment]
Oh cool! I haven't yet used any custom reporter before this one and had no idea the setting needs to re-include the "default" one. Thanks!

**Comment by rickhanlonii** [comment]
No sweat, enjoy!

**Comment by pedro-mass** [comment]
🤔 Didn't quite work as expected. Not sure if it's b/c of Typescript though.
Seems to work fine in normal mode, but not watch mode

![image](https://user-images.githubusercontent.com/1165961/47328532-66284900-d63f-11e8-99f3-bb6ef279bd3b.png)

Ended up passing it along as cli options, and making a separate script for it: 
```js
"test:skipped": "jest --reporters=\"default\" --reporters=\"jest-skipped-reporter\"",
```
